apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: mqtt-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mqtt-broker
    spec:
      containers:
      - name: mqtt-broker
        image: eclipse-mosquitto:1.4.12
        ports:
        - containerPort: 1883
        - containerPort: 1884
        volumeMounts:
        - name: config
          mountPath: /mosquitto/config/
      volumes:
      - name: config
        configMap:
          name: mqtt-broker-config