- hosts: debian
  roles:
    - debian

- hosts: auth
  roles:
    - auth
  vars:
    - CONTROLLER: "192.168.2.101"
    - K8S_NODES: [
    {"hostname":"worker1", "ip":"192.168.2.101"},
    {"hostname":"worker2", "ip":"192.168.2.102"},
    {"hostname":"worker3", "ip":"192.168.2.103"}
]
 
- hosts: etcd
  roles:
    - etcd
  vars:
    - ETCD_NODES: [ "192.168.2.101", "192.168.2.102", "192.168.2.103" ]

# - hosts: controller
#   roles:
#     - controller
# 
# - hosts: worker
#   roles:
#     - worker
# 
# - hosts: controller
#   roles:
#     - addons
# 