apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb-connector-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb-connector
    spec:
      containers:
      - name: mongodb-connector
        image: zsy9docker/kafka_mongodb_connector
        volumeMounts:
        - name: config
          mountPath: /opt/kafka/config/mongodb
      volumes:
      - name: config
        configMap:
          name: kafka-mongodb-connect-config