---
# tasks file for kafka-cluster

- name: cp yml files to the target machine
  synchronize:
    src: "{{ item }}"
    dest: kubernetes/{{ item }}
  with_items:
      - 'zookeeper/'
      - 'kafka/'
      - 'connector/'
      - 'mongo/'
      - 'mqtt/'
      - 'flask/'
      - 'create.sh'
      - 'delete.sh'

- name: start deploying k8s pods
  command: ./create.sh
  args:
    chdir: kubernetes/
  async: 600
  poll: 10