Vagrant.configure("2") do |config|
    config.vm.box = "debian/stretch64"
  
    config.vm.provider "virtualbox" do |v|
      v.memory = 1524
    end
  
    config.vm.define "debian-1", primary: true do |debian1|
      debian1.vm.network "private_network", ip: "192.168.2.101"
    end
    config.vm.define "debian-2" do |debian2|
      debian2.vm.network "private_network", ip: "192.168.2.102"
    end
    config.vm.define "debian-3" do |debian3|
      debian3.vm.network "private_network", ip: "192.168.2.103"
    end
  
  end