apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo-svc
  name: mongo-svc
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 32017
  selector:
    app: mongodb