---
# tasks file for addons
- name: mkdir for addons
  file:
    dest: ~/addons
    state: directory

- name: cp script files to the path
  copy:
    src: "{{ item }}"
    dest: ~/addons
    mode: +x
  with_items: 
    - 'setup_dns.sh'
    - 'busybox.yml'

- name: execute shell script for setting up addons
  shell: ~/addons/{{ item }}
  args:
    chdir: ~/addons/
  with_items:
    - 'setup_dns.sh'

- name: create busybox pod
  command: kubectl create -f ~/addons/busybox.yml
